- hosts: all
  tasks:
    - name: Remove Update Log Folder
      win_file:
        path: C:\AnsibleUpdateLog
        state: absent
  
    - name: Uninstall chocolatey packages
      win_chocolatey:
        name: "{{ item }}"
        msg: Installing "{{ item }}"
        state: absent
      with_items:
        - googlechrome
        - notepadplusplus.install
        - putty.install
          
    - name: Uninstall SysInternals
      win_chocolatey:
        name: sysinternals
        state: absent
        params: /InstallDir:C:\SysInternals
