- hosts:
    vm01
    vm02
  tasks:
    - name: Create Update Log Folder
      win_file:
        path: C:\AnsibleUpdateLog
        state: directory
  
    - name: Install chocolatey packages
      win_chocolatey:
        name: "{{ item }}"
        state: present
        force: yes
      with_items:
        - firefox
        - notepadplusplus.install
        - putty.install
          
    - name: Install SysInternals
      win_chocolatey:
        name: sysinternals
        state: present
        params: /InstallDir:C:\SysInternals
        
    - name: Set timezone to 'GMT Standard Time' (GMT)
      win_timezone:
        timezone: GMT Standard Time
        # Reboot when format, location or unicode has changed
        
    - name: Set format, location and unicode to English Australia and copy settings, reboot if required
      win_region:
        location: 242
        format: en-GB
        unicode_language: en-GB
        register: result
        
    - win_reboot:
        when: result.restart_required
